#!/bin/bash

# Quick Supabase Setup Script
# This script helps you set up your Supabase database

echo "🚀 Fikr Blog - Supabase Setup"
echo "=============================="
echo ""

echo "✅ Environment variables are configured!"
echo ""

echo "📋 Next Steps:"
echo ""
echo "1. Open your Supabase dashboard:"
echo "   https://supabase.com/dashboard/project/drwjrgthonfxgwoikegx"
echo ""
echo "2. Go to SQL Editor (left sidebar)"
echo ""
echo "3. Run these 3 migration files IN ORDER:"
echo "   a) Click 'New Query'"
echo "   b) Copy contents of: supabase/migrations/001_initial_schema.sql"
echo "   c) Paste and click 'Run'"
echo "   d) Repeat for: 002_rls_policies.sql"
echo "   e) Repeat for: 003_storage_buckets.sql"
echo ""
echo "4. Verify tables were created:"
echo "   - Go to 'Table Editor' (left sidebar)"
echo "   - You should see: profiles, posts, comments, likes, works, post_views"
echo ""
echo "5. Verify storage buckets:"
echo "   - Go to 'Storage' (left sidebar)"
echo "   - You should see: post-images, avatars, work-images"
echo ""
echo "6. Create your admin account:"
echo "   - Go to 'Authentication' → 'Users'"
echo "   - Click 'Add user' → 'Create new user'"
echo "   - Enter your email and password"
echo "   - Then run this SQL to make yourself admin:"
echo "     UPDATE profiles SET role = 'admin' WHERE email = 'your-email@example.com';"
echo ""
echo "Once complete, restart your dev server:"
echo "  npm run dev"
echo ""
echo "🎉 Then your blog will be connected to Supabase!"
